### ISSUE TITLE
Search only finds objects which start with the search term

### ISSUE THREAD

**Issue by twatzl** [james-windows/james#3]
For example when I search for 'Programmieren' I also want the folder 'PR_Programmieren' to be found. I usuaslly name my files like yyyy-dd-mm_<some name>.something. Those files are also not found when searching for <some name> using james.

PS: I tried to attach a screenshot, but it did not work.

**Comment by moser96** [comment]
This functionality is already implemented but currently not in production because it lacks stability.

https://github.com/james-windows/james/blob/master/SearchEngine/shared/SearchAlgorithm/search-engine.cpp#L508

**Comment by moser96** [comment]
Got fixed with the new SearchEngine! -> https://github.com/james-windows/james/commit/cad00611b90d4e43828f1acd9a749fe1b30e0fff
![image](https://cloud.githubusercontent.com/assets/13469452/20603834/a8fa884e-b263-11e6-8ab3-7ee0e9c176fd.png)

Sure the Engine is quite new and needs some more testing, but I will release a new binary soon!

**Comment by SimonLammer** [comment]
nice to see somebody is still working on it!
